/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iconnect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import static iconnect.login.userLogged;
import static iconnect.selectThread.selectedThread;
import java.sql.Statement;

/**
 *
 * @author ragulravindiran
 */
public class editThread extends javax.swing.JFrame {

    // create the connection with database
    Connection conn = new dbConnection().connect();

    /**
     * Creates new form editThread
     */
    public editThread() {
        initComponents();
        // setting the frame location to the middle
        setLocationRelativeTo(this);
        createMessage();
    }

    /**
     * method to add message to database
     */
    public void createMessage() {

        try {

            // sql statement to select message details
            String sql = "SELECT message, lastEditedTime, sentUser FROM `messages` WHERE `threadId` = '" + selectedThread + "'";
            PreparedStatement ps = conn.prepareStatement(sql);

            ResultSet resultSet = ps.executeQuery();
            DefaultTableModel dt = (DefaultTableModel) messageThread.getModel();
            dt.setColumnCount(3);
            System.out.println(sql);

            while (resultSet.next()) {
                Object obj[] = {resultSet.getString("message"), resultSet.getString("lastEditedTime"), resultSet.getString("sentUser")};
                System.out.println(resultSet.getString("message") + resultSet.getString("lastEditedTime") + resultSet.getString("sentUser"));
                dt.addRow(obj);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editThreadHeadLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        copyrightLbl = new javax.swing.JLabel();
        addThreadBtn = new javax.swing.JButton();
        messageLbl = new javax.swing.JLabel();
        lastEdit1Lbl = new javax.swing.JLabel();
        user1Lbl = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageThread = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        backToChatBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        editThreadHeadLbl.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        editThreadHeadLbl.setForeground(new java.awt.Color(255, 153, 0));
        editThreadHeadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editThreadHeadLbl.setText("#iConnect THREAD EDIT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(editThreadHeadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(editThreadHeadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        copyrightLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        copyrightLbl.setForeground(new java.awt.Color(255, 153, 0));
        copyrightLbl.setText("Copyright #iConnect, 2018");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(copyrightLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(copyrightLbl)
                .addContainerGap())
        );

        addThreadBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        addThreadBtn.setForeground(new java.awt.Color(102, 102, 102));
        addThreadBtn.setText("Add");
        addThreadBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addThreadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addThreadBtnActionPerformed(evt);
            }
        });

        messageLbl.setBackground(new java.awt.Color(0, 102, 153));
        messageLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        messageLbl.setForeground(new java.awt.Color(255, 153, 0));
        messageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLbl.setText("MESSAGE");
        messageLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        messageLbl.setOpaque(true);

        lastEdit1Lbl.setBackground(new java.awt.Color(0, 102, 153));
        lastEdit1Lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lastEdit1Lbl.setForeground(new java.awt.Color(255, 153, 0));
        lastEdit1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastEdit1Lbl.setText("LAST EDITED");
        lastEdit1Lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastEdit1Lbl.setOpaque(true);

        user1Lbl.setBackground(new java.awt.Color(0, 102, 153));
        user1Lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        user1Lbl.setForeground(new java.awt.Color(255, 153, 0));
        user1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1Lbl.setText("USER");
        user1Lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        user1Lbl.setOpaque(true);

        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });

        messageThread.setBackground(new java.awt.Color(51, 51, 51));
        messageThread.setForeground(new java.awt.Color(255, 153, 0));
        messageThread.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        messageThread.setRowHeight(28);
        messageThread.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageThreadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(messageThread);

        refreshBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(102, 102, 102));
        refreshBtn.setText("Refresh");
        refreshBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        backToChatBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        backToChatBtn.setForeground(new java.awt.Color(102, 102, 102));
        backToChatBtn.setText("Go Back to Chatrooms");
        backToChatBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backToChatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToChatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastEdit1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backToChatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addThreadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastEdit1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addThreadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(messageTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToChatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addThreadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addThreadBtnActionPerformed
        
        int threadSelected = selectedThread;
        String inputMessage = messageTextField.getText();
        String editedTime = new SimpleDateFormat("yyyy/MM/dd || HH:mm:ss").format(Calendar.getInstance().getTime());
        String inputUser = userLogged;

        // call threadEdit() from server
        threadEdit(threadSelected,inputMessage,editedTime,inputUser);
        
        editThread cleanUp = new editThread();
        this.dispose();
        cleanUp.setVisible(true);

    }//GEN-LAST:event_addThreadBtnActionPerformed

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void messageThreadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageThreadMouseClicked


        // set jTable to DefaultTableModel
        DefaultTableModel dtm = (DefaultTableModel) messageThread.getModel();
        int threadSelect = messageThread.getSelectedRow();
        selectedThread = Integer.parseInt(dtm.getValueAt(threadSelect, 0).toString());

        // check selected thread by threadId
        System.out.println("Selected thread :" + selectedThread);
    }//GEN-LAST:event_messageThreadMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        
        // refresh the jTable
        editThread refresh = new editThread();
        this.dispose();
        refresh.setVisible(true);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backToChatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToChatBtnActionPerformed
        
        this.dispose();
        // direct back to select thread page
        selectThread st = new selectThread();
        st.setVisible(true);
    }//GEN-LAST:event_backToChatBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addThreadBtn;
    private javax.swing.JButton backToChatBtn;
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JLabel editThreadHeadLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastEdit1Lbl;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JTable messageThread;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel user1Lbl;
    // End of variables declaration//GEN-END:variables

    private static void threadEdit(int thread, java.lang.String message, java.lang.String editedTime, java.lang.String editedUser) {
        iconnect.IConnectChatApp_Service service = new iconnect.IConnectChatApp_Service();
        iconnect.IConnectChatApp port = service.getIConnectChatAppPort();
        port.threadEdit(thread, message, editedTime, editedUser);
    }
}
