package iconnect;

import static iconnect.register.strAll;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ragulravindiran
 */
public class login extends javax.swing.JFrame {

    // create the connection with database
    Connection conn = new dbConnection().connect();

    // static varuable to store the user id
    static String userLogged;

    // static varuable to store the password
    static String inputPassword;

    /**
     * Creates new form login
     *
     */
    public login() {
        initComponents();
        // setting the frame location to the middle
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageLogoLbl = new javax.swing.JLabel();
        titleLogoLbl = new javax.swing.JLabel();
        copyrightLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        signInLogoLbl = new javax.swing.JLabel();
        loginIdLbl = new javax.swing.JLabel();
        loginId = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        toSignUpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        imageLogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconnect/images.png"))); // NOI18N

        titleLogoLbl.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        titleLogoLbl.setForeground(new java.awt.Color(255, 153, 0));
        titleLogoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLogoLbl.setText("#iConnect");

        copyrightLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        copyrightLbl.setForeground(new java.awt.Color(255, 153, 0));
        copyrightLbl.setText("Copyright #iConnect, 2018");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(titleLogoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(imageLogoLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(copyrightLbl)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(imageLogoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleLogoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyrightLbl)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        signInLogoLbl.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        signInLogoLbl.setForeground(new java.awt.Color(0, 102, 153));
        signInLogoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInLogoLbl.setText("Sign In");

        loginIdLbl.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        loginIdLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginIdLbl.setText("Login ID : ");

        loginId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIdActionPerformed(evt);
            }
        });

        passwordLbl.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        passwordLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLbl.setText("Password : ");

        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Don't have an account ? ");

        toSignUpBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        toSignUpBtn.setForeground(new java.awt.Color(0, 204, 102));
        toSignUpBtn.setText("Sign Up");
        toSignUpBtn.setBorder(null);
        toSignUpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toSignUpBtnMouseClicked(evt);
            }
        });
        toSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSignUpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(signInLogoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginIdLbl)
                                .addComponent(passwordLbl)
                                .addComponent(password)
                                .addComponent(loginId, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toSignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(signInLogoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(loginIdLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(passwordLbl)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(loginBtn)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(toSignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIdActionPerformed

    }//GEN-LAST:event_loginIdActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        // assign loginId to the static variable
        userLogged = loginId.getText();

        // assign password to the static variable
        inputPassword = password.getText();

        // check for empty fields
        if (userLogged.equals("") || inputPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the required fileds...!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // decrypting the password
        String decryptedPass = decryptPasswordVal(inputPassword, 3);;

        // call loginUI() from server
        if (loginUI(userLogged, decryptedPass)) {

            this.dispose();
            JOptionPane.showMessageDialog(null, "Login Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // direct to select thread if login is successful
            selectThread st = new selectThread();
            st.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(null, "Login Id or Password is Incorrect...!");
        }


    }//GEN-LAST:event_loginBtnActionPerformed

    private void toSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSignUpBtnActionPerformed

    }//GEN-LAST:event_toSignUpBtnActionPerformed

    private void toSignUpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toSignUpBtnMouseClicked

        // direct to sign up page if the user doesn't have an account
        this.dispose();
        register reg = new register();
        reg.show();

    }//GEN-LAST:event_toSignUpBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JLabel imageLogoLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginId;
    private javax.swing.JLabel loginIdLbl;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel signInLogoLbl;
    private javax.swing.JLabel titleLogoLbl;
    private javax.swing.JButton toSignUpBtn;
    // End of variables declaration//GEN-END:variables

    private static boolean loginUI(java.lang.String loginId, java.lang.String password) {
        iconnect.IConnectChatApp_Service service = new iconnect.IConnectChatApp_Service();
        iconnect.IConnectChatApp port = service.getIConnectChatAppPort();
        return port.loginUI(loginId, password);
    }

    /**
     * method to decrypt password
     * @param inputPassword
     * @param key
     * @return 
     */
    public static String decryptPasswordVal(String inputPassword, int key) {

        inputPassword = inputPassword.toLowerCase();
        String c = "";

        for (int i = 0; i < inputPassword.length(); i++) {

            int pos = strAll.indexOf(inputPassword.charAt(i));
            int keyValue = (pos + key) % 26;
            char repValue = strAll.charAt(keyValue);
            c = c + repValue;
        }
        return c;
    }

}
