/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iconnect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragulravindiran
 */
public class selectThread extends javax.swing.JFrame {

    // create the connection with database
    Connection conn = new dbConnection().connect();

    // static variable to store selected thread's ID
    static int selectedThread;

    /**
     * Creates new form selectThread
     */
    public selectThread() {
        initComponents();
        setLocationRelativeTo(this);
        createChatThread();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        threadHeadLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        copyrightLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        newThreadBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatThread = new javax.swing.JTable();
        threadTitleLbl = new javax.swing.JLabel();
        lastEditedLbl = new javax.swing.JLabel();
        editedByLbl = new javax.swing.JLabel();
        threadNo = new javax.swing.JLabel();
        toSignUpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        threadHeadLbl.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        threadHeadLbl.setForeground(new java.awt.Color(255, 153, 0));
        threadHeadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        threadHeadLbl.setText("#iConnect THREAD SELECT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(threadHeadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(threadHeadLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        copyrightLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        copyrightLbl.setForeground(new java.awt.Color(255, 153, 0));
        copyrightLbl.setText("Copyright #iConnect, 2018");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(copyrightLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(copyrightLbl)
                .addContainerGap())
        );

        editBtn.setBackground(new java.awt.Color(204, 204, 204));
        editBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(102, 102, 102));
        editBtn.setText("Edit Selected");
        editBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editBtn.setOpaque(true);
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        newThreadBtn.setBackground(new java.awt.Color(204, 204, 204));
        newThreadBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        newThreadBtn.setForeground(new java.awt.Color(102, 102, 102));
        newThreadBtn.setText("Create New Thread");
        newThreadBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newThreadBtn.setOpaque(true);
        newThreadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newThreadBtnMouseClicked(evt);
            }
        });
        newThreadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newThreadBtnActionPerformed(evt);
            }
        });

        chatThread.setBackground(new java.awt.Color(51, 51, 51));
        chatThread.setForeground(new java.awt.Color(255, 153, 0));
        chatThread.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chatThread.setRowHeight(28);
        chatThread.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatThreadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(chatThread);

        threadTitleLbl.setBackground(new java.awt.Color(0, 102, 153));
        threadTitleLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        threadTitleLbl.setForeground(new java.awt.Color(255, 153, 0));
        threadTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        threadTitleLbl.setText("TITLE");
        threadTitleLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        threadTitleLbl.setOpaque(true);

        lastEditedLbl.setBackground(new java.awt.Color(0, 102, 153));
        lastEditedLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lastEditedLbl.setForeground(new java.awt.Color(255, 153, 0));
        lastEditedLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastEditedLbl.setText("LAST EDITED");
        lastEditedLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastEditedLbl.setOpaque(true);

        editedByLbl.setBackground(new java.awt.Color(0, 102, 153));
        editedByLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        editedByLbl.setForeground(new java.awt.Color(255, 153, 0));
        editedByLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editedByLbl.setText("EDITED BY");
        editedByLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editedByLbl.setOpaque(true);

        threadNo.setBackground(new java.awt.Color(0, 102, 153));
        threadNo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        threadNo.setForeground(new java.awt.Color(255, 153, 0));
        threadNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        threadNo.setText("NO");
        threadNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        threadNo.setOpaque(true);

        toSignUpBtn.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        toSignUpBtn.setForeground(new java.awt.Color(255, 0, 0));
        toSignUpBtn.setText("Sign Out");
        toSignUpBtn.setBorder(null);
        toSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toSignUpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(newThreadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(threadNo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(threadTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastEditedLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editedByLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(toSignUpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threadTitleLbl)
                    .addComponent(lastEditedLbl)
                    .addComponent(editedByLbl)
                    .addComponent(threadNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newThreadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toSignUpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * method to create chat threads
     */
    private void createChatThread() {

        try {
            // sql statement to get all deatails of thread table
            String sql = "select * from threads";
            PreparedStatement prepareSta = conn.prepareStatement(sql);
            ResultSet resultSet = prepareSta.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) chatThread.getModel();
            dtm.setColumnCount(4);
            System.out.println(sql);

            while (resultSet.next()) {
                Object object[] = {resultSet.getInt("threadId"), resultSet.getString("threadTitle"), resultSet.getString("LastEdited"), resultSet.getString("User")};

                dtm.addRow(object);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void newThreadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newThreadBtnActionPerformed
        
    }//GEN-LAST:event_newThreadBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        
        this.dispose();
        // directs to edit thread page if btn is pressed
        editThread et = new editThread();
        et.show();
    }//GEN-LAST:event_editBtnMouseClicked

    private void newThreadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newThreadBtnMouseClicked
        
        this.dispose();
        // directs to create thread page if btn is pressed
        createThread ct = new createThread();
        ct.show();
    }//GEN-LAST:event_newThreadBtnMouseClicked

    private void chatThreadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatThreadMouseClicked

        // set jTable to Model
        DefaultTableModel dtm = (DefaultTableModel) chatThread.getModel();
        int threadSelect = chatThread.getSelectedRow();
        selectedThread = Integer.parseInt(dtm.getValueAt(threadSelect, 0).toString());
        
        // check selected thread by threadId
        System.out.println("Selected thread :" + selectedThread);
    }//GEN-LAST:event_chatThreadMouseClicked

    private void toSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toSignUpBtnActionPerformed
        
        // user gets logged out
        this.dispose();
        JOptionPane.showMessageDialog(null, "Logged Out Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        login ln = new login();
        ln.show();
    }//GEN-LAST:event_toSignUpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable chatThread;
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel editedByLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastEditedLbl;
    private javax.swing.JButton newThreadBtn;
    private javax.swing.JLabel threadHeadLbl;
    private javax.swing.JLabel threadNo;
    private javax.swing.JLabel threadTitleLbl;
    private javax.swing.JButton toSignUpBtn;
    // End of variables declaration//GEN-END:variables
}
